import * as stylex from '@stylexjs/stylex';

export const colors = stylex.defineVars({
  canvas: '#f7f8fa', paper: '#fff', ink: '#263630', muted: '#646f67', green: '#285b48', line: '#e5e8e6',
  butter: '#f8ebad', mint: '#dbebe1', lilac: '#eae4f3', peach: '#f6dfd2', danger: '#a03832',
});

export const styles = stylex.create({
  skipLink: { position: 'fixed', left: 16, top: -80, padding: 12, backgroundColor: 'white', zIndex: 30, ':focus': { top: 12 } },
  header: {
    position: 'sticky', top: 0, zIndex: 10, minHeight: 80, display: 'flex', alignItems: 'center', gap: 40, paddingInline: '5.55%', borderBottom: `1px solid ${colors.line}`, backgroundColor: '#fff',
    '@media (max-width: 700px)': { minHeight: 134, padding: '19px 22px 17px', gap: 16, display: 'grid', gridTemplateColumns: '1fr auto', backgroundColor: colors.canvas, borderBottomWidth: 0 },
  },
  brand: { display: 'flex', alignItems: 'center', gap: 12, textDecoration: 'none', fontSize: 38, lineHeight: 1, letterSpacing: -2, fontWeight: 800, minWidth: 200, '@media (max-width: 700px)': { fontSize: 32, gap: 10, minWidth: 0 } },
  brandMark: { display: 'block', position: 'relative', width: 34, height: 35, backgroundColor: '#f4d467', borderRadius: '8px 8px 12px 8px', transform: 'rotate(-8deg)', boxShadow: 'inset 0 -1px 0 #d6b84e', '@media (max-width: 700px)': { width: 29, height: 30 } },
  brandFold: { position: 'absolute', right: 0, bottom: 0, width: 12, height: 12, backgroundColor: '#d6b650', borderRadius: '5px 0 10px 0' },
  brandLine: { position: 'absolute', height: 2, width: 15, backgroundColor: '#786523', left: 9, top: 12, borderRadius: 2 },
  brandLineTwo: { top: 18, width: 10 },
  search: {
    maxWidth: 520, flex: 1, display: 'flex', alignItems: 'center', gap: 12, backgroundColor: colors.canvas, border: '1px solid #eef0ef', borderRadius: 10, paddingInline: 16, height: 46, color: colors.muted,
    ':focus-within': { outline: '2px solid #8eaa9f', outlineOffset: 2 },
    '@media (max-width: 700px)': { gridColumn: '1 / -1', gridRow: 2, width: '100%', maxWidth: 'none', height: 44, backgroundColor: '#eef0f1', paddingInline: 13 },
  },
  searchInput: { minWidth: 0, width: '100%', height: '100%', borderWidth: 0, backgroundColor: 'transparent', color: colors.ink, fontSize: 13, outline: 'none', '::placeholder': { color: '#757d79' }, '@media (max-width: 700px)': { fontSize: 16 } },
  searchKey: { fontSize: 11, minWidth: 22, height: 23, display: 'inline-grid', placeItems: 'center', border: '1px solid #dfe4e1', borderRadius: 4, color: colors.muted, '@media (max-width: 700px)': { display: 'none' } },
  accountActions: { marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 8, '@media (max-width: 700px)': { gap: 4 } },
  syncButton: { display: 'flex', alignItems: 'center', gap: 10, minHeight: 44, padding: 4, textAlign: 'left', fontSize: 12, color: '#526b5d', '@media (max-width: 700px)': { fontSize: 10, gap: 7 } },
  signOutButton: { minHeight: 44, paddingInline: 8, fontSize: 12, color: colors.muted, whiteSpace: 'nowrap', ':hover': { color: colors.green }, '@media (max-width: 700px)': { fontSize: 10, paddingInline: 4 } },
  workspace: { width: '88.9%', maxWidth: 1440, margin: '0 auto', paddingBlock: '28px calc(116px + env(safe-area-inset-bottom))', scrollMarginTop: 80, '@media (max-width: 1100px)': { width: 'calc(100% - 80px)' }, '@media (max-width: 700px)': { width: 'calc(100% - 40px)', paddingTop: 15, scrollMarginTop: 134 } },
  pageHeading: { marginBottom: 24 },
  h1: { fontSize: 32, letterSpacing: -1.3, margin: '0 0 6px', fontWeight: 800, '@media (max-width: 700px)': { fontSize: 28 } },
  section: { marginTop: 0 },
  sectionAfter: { marginTop: 20 },
  sectionHeading: { fontSize: 12, fontWeight: 700, color: colors.muted, margin: '0 0 14px' },
  board: { '--columns': 4, display: 'grid', gridTemplateColumns: 'repeat(var(--columns), minmax(0, 1fr))', gridAutoRows: '1px', columnGap: 20, margin: 0, padding: 0, listStyle: 'none', alignItems: 'start', '@media (min-width: 701px) and (max-width: 1100px)': { '--columns': 3, columnGap: 16 }, '@media (max-width: 700px)': { '--columns': 2, columnGap: 12 } },
  dropTarget: { outline: `2px dashed ${colors.green}`, outlineOffset: 3, borderRadius: 14 },
  dragPlaceholder: { opacity: 0.18 },
  noteItem: { minWidth: 0, position: 'relative', '@media (hover: hover) and (pointer: fine)': { '--pin-opacity': 0, ':hover': { '--pin-opacity': 1 }, ':focus-within': { '--pin-opacity': 1 } } },
  noteCard: { width: '100%', display: 'block', padding: 0, borderRadius: 14, backgroundColor: 'var(--note-color)', borderWidth: 1, borderStyle: 'solid', borderColor: '#26363013', overflow: 'clip', textAlign: 'left', position: 'relative', userSelect: 'none', cursor: 'grab', ':active': { cursor: 'grabbing' }, ':hover': { boxShadow: '0 4px 16px #2538300c', borderColor: '#26363040' }, '@media (max-width: 700px)': { borderRadius: 11 } },
  cardOverlay: { position: 'absolute', inset: 0, width: '100%', cursor: 'grab', ':active': { cursor: 'grabbing' }, ':focus-visible': { outline: `3px solid ${colors.green}`, outlineOffset: -3, zIndex: 2 } },
  linkedContent: { position: 'relative', pointerEvents: 'none' },
  noteLink: { position: 'relative', zIndex: 1, pointerEvents: 'auto', color: colors.green, textDecoration: 'underline', textUnderlineOffset: 2, cursor: 'pointer', ':focus-visible': { outline: `2px solid ${colors.green}`, outlineOffset: 2 } },
  paper: { '--note-color': colors.paper }, butter: { '--note-color': colors.butter }, mint: { '--note-color': colors.mint }, lilac: { '--note-color': colors.lilac }, peach: { '--note-color': colors.peach },
  noteContent: { display: 'block', padding: '22px 23px 17px', paddingRight: 54, '@media (max-width: 700px)': { padding: '15px 14px 13px', paddingRight: 46 } },
  imageContent: { padding: '15px 20px 16px', paddingRight: 54, '@media (max-width: 700px)': { padding: '12px 13px', paddingRight: 46 } },
  noteTitle: { display: '-webkit-box', WebkitBoxOrient: 'vertical', WebkitLineClamp: 2, overflow: 'hidden', fontSize: 17, fontWeight: 800, lineHeight: 1.5, marginBottom: 9, letterSpacing: -.25, overflowWrap: 'anywhere', '@media (max-width: 700px)': { fontSize: 15 }, '@media (max-width: 360px)': { fontSize: 14 } },
  noteBody: { display: '-webkit-box', WebkitBoxOrient: 'vertical', WebkitLineClamp: 4, overflow: 'hidden', fontSize: 14, lineHeight: 1.85, whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', '@media (max-width: 360px)': { fontSize: 13 } },
  photo: { display: 'block', width: '100%', height: 'auto', maxHeight: 420, objectFit: 'contain' },
  imageMosaic: { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gridTemplateRows: 'repeat(2, minmax(0, 1fr))', gap: 4, width: '100%', aspectRatio: '4 / 3', overflow: 'hidden', '@media (max-width: 700px)': { gap: 3 } },
  mosaicTwo: { gridTemplateRows: '1fr' },
  mosaicWide: { gridColumn: '1 / -1' },
  mosaicTile: { position: 'relative', display: 'block', minWidth: 0, minHeight: 0, overflow: 'hidden' },
  mosaicPhoto: { display: 'block', width: '100%', height: '100%', objectFit: 'cover' },
  mosaicOpen: { display: 'block', width: '100%', height: '100%', padding: 0, ':focus-visible': { outline: `3px solid ${colors.green}`, outlineOffset: -3 } },
  mosaicMore: { position: 'absolute', right: 6, bottom: 6, display: 'flex', alignItems: 'center', gap: 5, padding: '5px 7px', borderRadius: 6, backgroundColor: '#263630e0', color: '#fff', fontSize: 11, lineHeight: 1.2, pointerEvents: 'none', '@media (max-width: 700px)': { right: 3, bottom: 3, padding: 4, gap: 3, fontSize: 10 } },
  pin: { position: 'absolute', right: 6, top: 4, width: 44, height: 44, display: 'grid', placeItems: 'center', borderRadius: 8, color: colors.muted, backgroundColor: '#ffffffc9', ':hover': { backgroundColor: '#e6ebe8' } },
  pinVisibility: { '@media (hover: none)': { display: 'none' }, '@media (hover: hover) and (pointer: fine)': { opacity: 'var(--pin-opacity)' }, ':focus-visible': { opacity: 1 } },
  pinned: { color: colors.green },
  contextMenu: { position: 'fixed', zIndex: 40, width: 176, padding: 6, border: `1px solid ${colors.line}`, borderRadius: 10, backgroundColor: '#fff', boxShadow: '0 12px 32px #18251e30' },
  contextMenuItem: { display: 'block', width: '100%', minHeight: 40, paddingInline: 12, textAlign: 'left', borderRadius: 6, fontSize: 13, color: colors.ink, ':hover': { backgroundColor: '#edf0ee' }, ':focus-visible': { outline: `2px solid ${colors.green}`, outlineOffset: -2 } },
  contextMenuDanger: { display: 'block', width: '100%', minHeight: 40, paddingInline: 12, textAlign: 'left', borderRadius: 6, fontSize: 13, color: colors.danger, ':hover': { backgroundColor: '#f9eeec' }, ':focus-visible': { outline: `2px solid ${colors.danger}`, outlineOffset: -2 } },
  empty: { textAlign: 'center', padding: '80px 20px', color: colors.muted },
  floatingCapture: { position: 'fixed', display: 'flex', alignItems: 'center', bottom: 'calc(20px + env(safe-area-inset-bottom))', left: '50%', transform: 'translateX(-50%)', width: 'max-content', maxWidth: 'calc(100% - 32px)', height: 58, backgroundColor: colors.green, borderRadius: 18, color: '#fff', padding: 6, boxShadow: '0 6px 20px #285b4833', zIndex: 5 },
  mobileButton: { height: 48, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 9, color: '#fff', fontSize: 13, fontWeight: 700, paddingInline: 19, whiteSpace: 'nowrap', borderRadius: 12 },
  mobileDivider: { height: 24, width: 1, backgroundColor: '#ffffff30' },
  dialog: { color: colors.ink, border: `1px solid ${colors.line}`, boxShadow: '0 20px 100px #18251e30', borderRadius: 18, padding: 0, backgroundColor: '#fff', maxHeight: '90dvh', '::backdrop': { backgroundColor: '#26363055', backdropFilter: 'blur(3px)' } },
  editor: { width: 'min(960px, calc(100% - 40px))', height: 'min(820px, calc(100dvh - 48px))', backgroundColor: 'var(--note-color)', '@media (max-width: 700px)': { margin: 0, width: '100%', height: '100dvh', maxHeight: '100dvh', maxWidth: '100%', borderRadius: 0, borderWidth: 0 } },
  editorForm: { display: 'flex', flexDirection: 'column', height: '100%', maxHeight: '90dvh', '@media (max-width: 700px)': { height: '100%', maxHeight: '100dvh', paddingTop: 'env(safe-area-inset-top)', paddingBottom: 'env(safe-area-inset-bottom)' } },
  editorHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, padding: '14px 18px 12px 28px', fontSize: 12, color: '#546358', '@media (max-width: 700px)': { paddingLeft: 24 } },
  noteTimestamps: { display: 'flex', flexDirection: 'column', gap: 2, minWidth: 0, lineHeight: 1.4 },
  headerActions: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0, marginLeft: 'auto' },
  pinText: { display: 'flex', alignItems: 'center', justifyContent: 'center', width: 44, height: 44, borderRadius: 8, ':hover': { backgroundColor: '#2636300c' } },
  iconButton: { width: 44, height: 44, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', borderRadius: 8, ':hover': { backgroundColor: '#2636300c' } },
  editorFields: { display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, padding: '8px 30px 12px', overflow: 'auto', '@media (max-width: 700px)': { padding: '8px 24px 16px' } },
  titleInput: { borderWidth: 0, backgroundColor: 'transparent', width: '100%', color: colors.ink, fontSize: 25, fontWeight: 700, lineHeight: 1.6 },
  bodyInput: { borderWidth: 0, backgroundColor: 'transparent', width: '100%', color: colors.ink, flex: 1, minHeight: 200, fontSize: 16, lineHeight: 1.9, marginTop: 16, resize: 'none', overflow: 'auto', '@media (max-width: 700px)': { minHeight: 160 } },
  editorImages: { display: 'flex', overflowX: 'hidden', overflowY: 'auto', paddingInline: 30, flexShrink: 0, maxHeight: 'min(440px, 45dvh)', alignItems: 'flex-start' },
  editorMosaic: { width: 'calc(100% - 60px)', maxWidth: 520, margin: '0 auto 8px', borderRadius: 8, aspectRatio: '2.3 / 1', flexShrink: 0, '@media (max-width: 700px)': { width: 'calc(100% - 48px)' } },
  editorImageCentered: { marginLeft: 'auto' },
  editorImageEnd: { marginRight: 'auto' },
  editorImage: { position: 'relative', maxWidth: '100%', flexShrink: 1 },
  photoButton: { display: 'block', maxWidth: '100%', padding: 0, borderRadius: 8, cursor: 'zoom-in', ':focus-visible': { outline: `3px solid ${colors.green}`, outlineOffset: 2 } },
  editorPhoto: { display: 'block', maxWidth: '100%', maxHeight: 'min(440px, 45dvh)', width: 'auto', height: 'auto', objectFit: 'contain', borderRadius: 8 },
  previewDialog: {
    position: 'fixed', width: 'min(1100px, calc(100% - 64px))', height: 'min(860px, 90dvh)', maxWidth: 'none', maxHeight: 'none', padding: 24,
    border: 0, borderRadius: 16, backgroundColor: '#1d2823', color: '#fff', boxShadow: '0 20px 100px #0007',
    '::backdrop': { backgroundColor: '#101a16c9' },
    '@media (max-width: 700px)': { width: '100%', height: '100dvh', padding: 'calc(56px + env(safe-area-inset-top)) 16px calc(32px + env(safe-area-inset-bottom))', borderRadius: 0 },
  },
  previewStage: { width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  previewImage: { position: 'relative', maxWidth: '100%', maxHeight: '100%' },
  previewPhoto: { width: 'auto', height: 'auto', maxWidth: '100%', maxHeight: 'calc(min(860px, 90dvh) - 48px)', objectFit: 'contain', display: 'block', '@media (max-width: 700px)': { maxHeight: 'calc(100dvh - 96px - env(safe-area-inset-top) - env(safe-area-inset-bottom))' } },
  previewClose: { position: 'absolute', top: 12, right: 12, width: 44, height: 44, display: 'grid', placeItems: 'center', borderRadius: 8, backgroundColor: '#ffffff24', color: '#fff', ':hover': { backgroundColor: '#ffffff40' }, '@media (max-width: 700px)': { top: 'calc(8px + env(safe-area-inset-top))', right: 12 } },
  previewRemove: { position: 'absolute', top: 8, right: 8, width: 44, height: 44, display: 'grid', placeItems: 'center', borderRadius: 8, backgroundColor: '#1d2823cc', color: '#fff', ':hover': { backgroundColor: '#1d2823' } },
  previewPrevious: { position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', width: 44, height: 44, display: 'grid', placeItems: 'center', borderRadius: 8, backgroundColor: '#ffffff24', color: '#fff', ':hover': { backgroundColor: '#ffffff40' } },
  previewNext: { position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)', width: 44, height: 44, display: 'grid', placeItems: 'center', borderRadius: 8, backgroundColor: '#ffffff24', color: '#fff', ':hover': { backgroundColor: '#ffffff40' } },
  previewCount: { position: 'absolute', bottom: 8, left: '50%', transform: 'translateX(-50%)', color: '#fff', fontSize: 13 },
  editorFooter: { padding: '14px 18px', borderTop: '1px solid #26363012', display: 'flex', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap', '@media (max-width: 700px)': { padding: 12, gap: 6 } },
  tools: { display: 'flex', alignItems: 'center', gap: 8 },
  colorPickerAnchor: { position: 'relative' },
  colorPopover: { position: 'absolute', bottom: 'calc(100% + 8px)', left: 0, zIndex: 2, padding: 14, border: `1px solid ${colors.line}`, borderRadius: 12, backgroundColor: '#fff', boxShadow: '0 8px 28px #18251e30' },
  colorPicker: { display: 'flex', gap: 10, borderWidth: 0, padding: 0, margin: 0 },
  swatch: { display: 'grid', placeItems: 'center', width: 36, height: 36, backgroundColor: 'var(--note-color)', borderStyle: 'solid', borderWidth: 1, borderColor: '#26363040', borderRadius: '50%', cursor: 'pointer' },
  paperSwatch: { borderWidth: 2, borderColor: '#66786b' },
  swatchSelected: { outline: `2px solid ${colors.green}`, outlineOffset: 2 },
  radio: { appearance: 'none', margin: 0, width: 36, height: 36, cursor: 'pointer' },
  error: { fontSize: 12, color: colors.danger, paddingInline: 30, margin: 0 },
  primary: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8, minHeight: 44, paddingInline: 20, borderRadius: 9, fontSize: 13, fontWeight: 700, color: '#fff', backgroundColor: colors.green, ':hover': { backgroundColor: '#1e4939' } },
  secondary: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', minHeight: 44, paddingInline: 20, borderRadius: 9, fontSize: 13, fontWeight: 700, backgroundColor: '#edf0ee' },
  danger: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', minHeight: 44, paddingInline: 20, borderRadius: 9, fontSize: 13, fontWeight: 700, backgroundColor: colors.danger, color: 'white' },
  deleteIcon: { color: colors.danger },
  smallDialog: { width: 'min(430px, calc(100% - 32px))', padding: 30 },
  dialogTitle: { fontSize: 22, letterSpacing: -.6, margin: '0 0 12px' },
  dialogCopy: { fontSize: 13, color: '#637067', lineHeight: 1.8 },
  dialogActions: { display: 'flex', justifyContent: 'flex-end', gap: 10, marginTop: 24 },
  updateNotice: { position: 'fixed', bottom: 24, left: '50%', transform: 'translateX(-50%)', zIndex: 25, width: 'min(540px, calc(100% - 32px))', display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap', padding: '14px 18px', borderRadius: 12, backgroundColor: colors.ink, color: '#fff', boxShadow: '0 8px 24px #0003', fontSize: 13, '@media (max-width: 700px)': { bottom: 'calc(92px + env(safe-area-inset-bottom))' } },
  updateButton: { minHeight: 44, paddingInline: 14, borderRadius: 8, backgroundColor: colors.butter, color: colors.ink, fontWeight: 700, whiteSpace: 'nowrap', ':disabled': { opacity: 0.5 } },
  updateDismiss: { minHeight: 44, paddingInline: 8, color: '#fff' },
  toast: { position: 'fixed', bottom: 'calc(92px + env(safe-area-inset-bottom))', left: '50%', transform: 'translateX(-50%)', backgroundColor: colors.ink, color: '#fff', padding: '13px 22px', borderRadius: 10, fontSize: 12, zIndex: 20, boxShadow: '0 4px 16px #0002', maxWidth: 'calc(100% - 32px)', textAlign: 'center' },
  loginPage: { minHeight: '100dvh', display: 'grid', placeItems: 'center', padding: 24, backgroundColor: colors.canvas },
  loginCard: { width: 'min(420px, 100%)', padding: 32, border: `1px solid ${colors.line}`, borderRadius: 18, backgroundColor: '#fff', boxShadow: '0 12px 50px #26363012' },
  loginTitle: { fontSize: 30, margin: '24px 0 8px' },
  loginCopy: { color: colors.muted, lineHeight: 1.6, fontSize: 14 },
  password: { width: '100%', height: 48, border: `1px solid ${colors.line}`, borderRadius: 9, paddingInline: 14, marginBlock: '18px 10px', backgroundColor: colors.canvas },
  fullButton: { width: '100%' },
  statusRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 18, fontSize: 12, color: colors.muted },
});
